sudo: false

addons:
  apt:
    - libfreetype6-dev
    - libglew-dev
    - libmpfr-dev
    - libxft-dev
    - libxrender-dev
    - lintian

language: cpp

script: ./configure --disable-maintainer-mode && make && VERBOSE=1 make check
