.TH POTTYTEXT 1 "May 2007" 
.PP 
.SH "NAME" 
pottytext \- an x11 terminal emulator
.PP 
.SH "SYNOPSIS" 
.PP 
\fBpottytext
.PP 
.SH "DESCRIPTION" 
.PP 
\fBpottytext\fP is the terminal emulator from \fBpotty\fP(1) without the built-in
window manager and other functionality.  It's relatively featureless; only UTF-8
is supported, there is no scrollback buffer and no menus.
.PP
.SH "AUTHOR"  
.PP  
This manual page was written by Morten Hustveit <morten@rashbox.org>.
