.TH CANTERA-TERM 1 "May 2007"
.PP 
.SH "NAME" 
cantera-term \- an x11 terminal emulator
.PP 
.SH "SYNOPSIS" 
.PP 
\fBcantera-term
.PP 
.SH "DESCRIPTION" 
.PP 
\fBcantera-term\fP is an X11 terminal emulator.  Only UTF-8 is supported, there
is no scrollback buffer and no menus.  It has special functionality for viewing
images inside the scrolling buffer.
.PP
.SH "AUTHOR"  
.PP  
This manual page was written by Morten Hustveit <morten@rashbox.org>.
