.TH CANTERA 1 "March 2009" 
.PP 
.SH "NAME" 
canetera-wm \- the Canetera window manager
.PP 
.SH "SYNOPSIS" 
.PP 
\fBcantera-wm
.PP 
.SH "DESCRIPTION" 
.PP 
\fBcanetera-wm\fP is an X11 window manager.  It only supports fullscreen
windows and keyboard navigation.
.PP
.SH "AUTHOR"  
.PP  
This manual page was written by Morten Hustveit <morten@rashbox.org>.
