#ifndef TEXTURE_H_
#define TEXTURE_H_ 1

/**
 * Loads an image file.
 *
 * Returns a texture handle generated by glGenTextures()
 *
 * If the texture is already loaded, return the previously generated handle.
 */
int texture_load(const char* path);

/**
 * Returns the dimensions of a texture.
 *
 * You can set `width' or `height' to NULL if you only want the size in one
 * dimension.
 */
void texture_size(int handle, int* width, int* height);

#endif
